name: Lighthouse CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Preview (serve dist)
        run: npx serve -s dist -l 4173 &

      - name: Wait for preview
        run: npx wait-on http://localhost:4173

      - name: Run Lighthouse CI
        run: npx @lhci/cli@0.12.0 autorun --collect.url=http://localhost:4173

      - name: Upload LHCI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci

